### ISSUE TITLE
Meta: Review all existing FOSS projects against plugin skeleton standards.

### ISSUE THREAD

**Issue by beporter** [loadsys/CakePHP-Plugin-Skeleton#23]
Using this list as a starting point, all projects should be brought in line with this skeleton's basic standards:

https://github.com/loadsys?utf8=%E2%9C%93&query=CakePHP-

This should be done once most of the other currently open issues are resolved. That currently includes:
- [ ] Add Travis Template For Cake 3.x #3
- [ ] Add Composer.json Template for Cake 3.x #5
- [ ] Update Readme with instructions to setup Travis - Cake 3.x #6
- [ ] Add Packagist Setup Instructions - Cake 3.x Branches #7
- [ ] Update Readme with instructions to setup Coveralls - Cake 3.x #8
- [ ] Get a Basic Skeleton for Cake 3 #9
- [ ] Add a default Code of Conduct. #19
- [ ] Add instructions for using `composer create-project`? #22
